// <auto-generated />
using Maiboroda_Flowers.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Maiboroda_Flowers.Migrations
{
    [DbContext(typeof(DbOrderContext))]
    [Migration("20241103172413_Orders")]
    partial class Orders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Maiboroda_Flowers.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressRecipient")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressSender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CityRecipient")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CitySender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateReceipt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ProductWeight")
                        .HasColumnType("NUMERIC");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "IX_Orders_Id")
                        .IsUnique();

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
